name: steam-new-store-rss

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: steam-rss
  cancel-in-progress: true

permissions:
  contents: write
  actions: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) 前回のstateをArtifactから復元（無ければスキップ）
      - name: Restore state from latest artifact (if exists)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p state
          gh run download -n state -D state || echo "no previous state"

      # 2) 初回移行用（任意）：repo直下の state.json を一度だけ gzip化して種にする
      - name: Seed from repo state.json (one-time, optional)
        if: ${{ hashFiles('state.json') != '' }}
        run: |
          if [ ! -f state/state.json.gz ]; then
            mkdir -p state
            python -c "import json,gzip,os; s=json.load(open('state.json','r',encoding='utf-8')); os.makedirs('state',exist_ok=True); f=gzip.open('state/state.json.gz','wt',encoding='utf-8'); json.dump(s,f,ensure_ascii=False,separators=(',',':')); f.close()"
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

- name: Fast-forward state cursor (hot tail)
  env:
    STATE_PATH: state/state.json.gz        # --state-path と合わせる
    HOT_TAIL_START: '262000'               # 末尾の少し手前（例：cursor_max-20000）
  run: |
    python - <<'PY'
    import os, json, gzip, pathlib, sys
    state_path = os.environ.get("STATE_PATH", "state/state.json.gz")
    target = int(os.environ.get("HOT_TAIL_START", "262000"))  # 例示値

    def load(path):
      if not os.path.exists(path): return {}
      if path.endswith(".gz"):
        with gzip.open(path, "rt", encoding="utf-8") as f: return json.load(f)
      with open(path, "r", encoding="utf-8") as f: return json.load(f)

    def dump(path, data):
      pathlib.Path(os.path.dirname(path) or ".").mkdir(parents=True, exist_ok=True)
      if path.endswith(".gz"):
        with gzip.open(path, "wt", encoding="utf-8") as f: json.dump(data, f, ensure_ascii=False)
      else:
        with open(path, "w", encoding="utf-8") as f: json.dump(data, f, ensure_ascii=False)

    st = load(state_path) or {}
    st.setdefault("seen", {})
    st.setdefault("cursor", 0)
    before = st["cursor"]
    if before < target:
      st["cursor"] = target
    dump(state_path, st)
    print(f"cursor: {before} -> {st['cursor']}  (seen={len(st['seen'])})")
    PY


      - name: Run script
        run: python steam_new_store_rss.py --state-path "state/state.json.gz"

      # 3) 今回のstateを保存
      - name: Save state as artifact
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state/state.json.gz
          retention-days: 90

      # 4) RSSのみcommit/push（Pages更新用）
      - name: Commit & Push RSS
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add steam_new_store.xml feed_*.xml || true
          git commit -m "update feeds [skip ci]" || true
          git pull --rebase || true
          git push
