name: steam-new-store-rss

on:
  schedule:
    - cron: "*/30 * * * *"
  workflow_dispatch:

concurrency:
  group: steam-rss
  cancel-in-progress: true

permissions:
  contents: write     # RSSをcommit/push
  actions: read       # 過去ランのArtifactを取得

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 1) 前回のstateをArtifactから復元（無ければスキップ）
      - name: Restore state from latest artifact (if exists)
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p state
          gh run download -n state -D state || echo "no previous state"

      # （初回移行用・任意）repo直下の state.json があれば一度だけ種にする
      - name: Seed from repo state.json (one-time, optional)
        run: |
          if [ -f state.json ] && [ ! -f state/state.json.gz ]; then
            mkdir -p state
            python - <<'PY'
import json, gzip
with open('state.json','r',encoding='utf-8') as f:
    s=json.load(f)
with gzip.open('state/state.json.gz','wt',encoding='utf-8') as g:
    import json; g.write(json.dumps(s, ensure_ascii=False, separators=(',',':')))
PY
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install deps
        run: pip install -r requirements.txt

      - name: Run script
        run: python steam_new_store_rss.py --state-path "state/state.json.gz"

      # 2) 今回のstateを保存（同一ジョブ内で同名に複数回アップは不可）
      - name: Save state as artifact
        uses: actions/upload-artifact@v4
        with:
          name: state
          path: state/state.json.gz
          retention-days: 90

      # 3) RSSのみcommit/push（Pages更新用）
      - name: Commit & Push RSS
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add steam_new_store.xml feed_*.xml || true
          git commit -m "update feeds [skip ci]" || true
          git push
