name: steam-new-store-rss
on:
  schedule:
    - cron: "*/30 * * * *"   # 30分おきに実行（必要に応じて調整）
  workflow_dispatch:

permissions:
  contents: write  # GITHUB_TOKEN で push するため

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run detector (baseline on first run)
        run: |
          python steam_new_store_rss.py \
            --state state.json \
            --rss-out steam_new_store.xml \
            --pending-retry 200 \
            --max-new 500 \
            --baseline-if-empty \
            --cc jp --lang ja \
            --channel-title "New on Steam（画像＋説明つき / JA→EN）"

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json steam_new_store.xml
            git commit -m "Update RSS: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
