name: steam-new-store-rss

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分おき
  workflow_dispatch:

# 同時実行を防ぐ（前回が長引いたら新しい方を優先）
concurrency:
  group: steam-rss
  cancel-in-progress: true

permissions:
  contents: write  # GITHUB_TOKEN で push するため

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 軽いジッター（毎回同時刻集中を避ける）
      - name: Jitter
        run: python -c "import time, random; time.sleep(random.uniform(0,30))"

      - name: (ONE-TIME) Retitle past new-store items with suffix
        run: |
          python -c "import json,os; p='state.json'; \
s=json.load(open(p,encoding='utf-8')) if os.path.exists(p) else None; \
cnt=0; \
if s: \
    for it in s.get('items', []): \
        g=str(it.get('guid','')); \
        if g.startswith('steam-store-published-'): \
            t=it.get('title') or '(no title)'; \
            if '新規追加' not in t: \
                it['title']=t+'（新規追加）'; cnt+=1; \
    json.dump(s, open(p,'w',encoding='utf-8'), ensure_ascii=False, indent=2); \
print('retitled',cnt,'items')"


      - name: Run detector (baseline on first run)
        run: |
          python steam_new_store_rss.py \
            --state state.json \
            --rss-out steam_new_store.xml \
            --updates-out steam_store_updates.xml \
            --pending-retry 100 \
            --max-new 200 \
            --crawl-batch 600 \
            --baseline-if-empty \
            --cc jp --lang ja \
            --channel-title "Himat版 Steam 新規ストア公開（画像＋説明）" \
            --updates-title "Steam Store 更新イベント（価格・言語含む）" \
            --updates-desc "Steamストアのメタデータ変更（価格・言語・画像・説明など）を検知して通知"

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json steam_new_store.xml steam_store_updates.xml
            git commit -m "Update RSS: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
