name: steam-new-store-rss

on:
  schedule:
    - cron: "*/20 * * * *"   # 20分おき（UTC基準）
  workflow_dispatch:

# 同時実行を避けつつ、キャンセルはしない（新しいものはキューで待機）
concurrency:
  group: steam-rss
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
      - name: Show trigger & times
        run: |
          echo "event=${{ github.event_name }}"
          echo "schedule=${{ github.event.schedule }}"
          echo "UTC:   $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Local: $(date    '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run crawler
        run: |
          set -euxo pipefail
          python -V
          python main.py

      - name: List outputs (debug)
        run: |
          echo "== repo root =="
          ls -lah || true
          echo "== snapshots =="
          ls -lah snapshots || true
          echo "== snapshots/new =="
          ls -lah snapshots/new || true
          echo "== snapshots/updates =="
          ls -lah snapshots/updates || true
          echo "== show head of feeds =="
          head -n 20 feed_new.xml || true
          head -n 20 feed_updates.xml || true
          echo "== show state =="
          head -n 50 state.json || true

      - name: Commit & push if changed
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # 生成物だけをホワイトリストでステージ
          for f in state.json feed_new.xml feed_updates.xml; do
            if [ -f "$f" ]; then git add "$f"; fi
          done
          git add "snapshots/new/*.jsonl.gz"      2>/dev/null || true
          git add "snapshots/updates/*.jsonl.gz"  2>/dev/null || true

          # 何かステージされていればコミット＆プッシュ
          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "update feeds/state/snapshots: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            git pull --rebase --autostash || true
            git push
          fi
