name: steam-new-store-rss

on:
  schedule:
    - cron: "*/30 * * * *"   # 30分おき（UTC基準）
  workflow_dispatch:

# 同時実行を防止（長引いた場合は新しい方を優先）
concurrency:
  group: steam-rss
  cancel-in-progress: true

permissions:
  contents: write

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Show trigger & times
        run: |
          echo "event=${{ github.event_name }}"
          echo "UTC:   $(date -u '+%Y-%m-%d %H:%M:%S')"
          echo "Local: $(date    '+%Y-%m-%d %H:%M:%S')"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install -U pip
          pip install requests

      - name: Run steam_new_store_rss.py
        run: |
          python steam_new_store_rss.py

      - name: Show outputs
        run: |
          ls -l
          tail -n +1 feed_new.xml feed_updates.xml | head -n 50 || true

      - name: Commit & Push
        run: |
          set -euxo pipefail
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # .gitignoreにstate.jsonが書かれていても強制追加
          git add -f state.json feed_new.xml feed_updates.xml || true

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git commit -m "update feeds & state [skip ci]" || true
          git fetch origin
          git pull --rebase
          git push
