name: steam-new-store-rss
on:
  schedule:
    - cron: "*/30 * * * *"   # 30分おきに実行（必要に応じて調整）
  workflow_dispatch:

permissions:
  contents: write  # GITHUB_TOKEN で push するため

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          
      - name: (ONE-TIME) Insert known app to pending for verification
        run: |
          python - <<'PY'
          import json, os
          P = 'state.json'
          if os.path.exists(P):
              s = json.load(open(P, encoding='utf-8'))
          else:
              s = {"seen": {}, "pending": [], "items": []}
          # Dota 2 (570) を pending に入れる（存在しなければ）
          if 570 not in s.get("pending", []):
              s.setdefault("pending", []).append(570)
          s.setdefault("seen", {}).setdefault("570", {"published": False, "detected_at": None})
          json.dump(s, open(P, 'w', encoding='utf-8'), ensure_ascii=False, indent=2)
          print("Inserted 570 into pending")
          PY
          
      - name: Run detector (baseline on first run)
        run: |
          python steam_new_store_rss.py \
            --state state.json \
            --rss-out steam_new_store.xml \
            --pending-retry 200 \
            --max-new 500 \
            --baseline-if-empty \
            --cc jp --lang ja \
            --channel-title "New on Steam（画像＋説明つき / JA→EN）"

      - name: Commit & push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add state.json steam_new_store.xml
            git commit -m "Update RSS: $(date -u '+%Y-%m-%dT%H:%M:%SZ')"
            git push
          fi
